[profile.default]
src = 'src'
out = 'out'
# A list of paths to look for libraries in
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]

# A list of remappings
remappings = []
# Whether to autodetect remappings by scanning the `libs` folders recursively
auto_detect_remappings = true

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false

# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.13'

[fuzz]
runs = 1000

[rpc_endpoints]
# This section lives outside of profiles and defines a table of RPC endpoints, where the key specifies the RPC endpoints's name and the value is the RPC endpoint itself.
# The value can either be a valid RPC endpoint or a reference to an environment variable (wrapped with in ${}).
# These RPC endpoints can be used in tests and Solidity scripts 
mainnet = "${RPC_URL}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4